name: PHP Test/Analyse

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpstan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-dev-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-dev-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --dev

      - name: PHPSTAN
        run: vendor/bin/phpstan analyse src
